name: tf
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - astor=0.8.0
  - attrs=19.3.0
  - audioread=2.1.8
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.2
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.2.2
  - gettext=0.19.8.1
  - glib=2.63.1
  - gmp=6.1.2
  - google-pasta=0.2.0
  - grpcio=1.27.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.2
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.1.0
  - lame=3.100
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libflac=1.3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libogg=1.3.2
  - libopus=1.3
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - librosa=0.7.2
  - libsndfile=1.0.28
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libvorbis=1.3.6
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.31.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - ncurses=6.2
  - notebook=6.0.3
  - numba=0.48.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openh264=1.8.0
  - openssl=1.1.1f
  - opt_einsum=3.1.0
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - portaudio=19.6.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - protobuf=3.11.4
  - ptyprocess=0.6.0
  - pyaudio=0.2.11
  - pycparser=2.20
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysoundfile=0.10.2
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2019.3
  - qt=5.9.7
  - qtconsole=4.7.2
  - qtpy=1.9.0
  - readline=8.0
  - resampy=0.2.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.1.3
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tbb=2020.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - x264=1!152.20180806
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - pip:
      - imbalanced-learn==0.6.2
      - pillow==7.1.1
      - pygame==1.9.6
prefix: /home/fm-pc-lt-150/miniconda3/envs/tf
