name: tf
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - audioread=2.1.8
  - backcall=0.1.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.2
  - freetype=2.10.1
  - gettext=0.19.8.1
  - glib=2.58.3
  - gmp=6.1.2
  - gnutls=3.6.5
  - icu=64.2
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2019.4
  - ipykernel=5.2.0
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.2
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.1.0
  - lame=3.100
  - libcxx>=4.0.1
  - libcxxabi>=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran<=3.0.1
  - libiconv=1.15
  - libpng=1.6.37
  - librosa=0.6.1
  - libsodium=1.0.17
  - llvm-openmp=10.0.0
  - llvmlite=0.31.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - ncurses=6.2
  - nettle=3.4.1
  - notebook=6.0.3
  - numba=0.48.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openh264=1.8.0
  - openssl=1.1.1f
  - pandas=1.0.3
  - pandoc=2.9.2
  - parso=0.6.2
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - portaudio=19.6.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - pyaudio=0.2.11
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2019.3
  - qt=5.9.7
  - qtconsole=4.7.2
  - qtpy=1.9.0
  - readline=8.0
  - resampy=0.2.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.1.3
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tbb=2018.0.5
  - testpath=0.4.4
  - tk=8.6.8
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - x264=1!152.20180806
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - altair==4.1.0
    - astor==0.8.1
    - base58==2.0.0
    - bleach==1.5.0
    - blinker==1.4
    - boto3==1.12.39
    - botocore==1.15.39
    - cachetools==4.1.0
    - chardet==3.0.4
    - click==7.1.1
    - docutils==0.15.2
    - enum-compat==0.0.3
    - future==0.18.2
    - gast==0.3.3
    - grpcio==1.28.1
    - h5py==2.10.0
    - html5lib==0.9999999
    - idna==2.9
    - imbalanced-learn==0.6.2
    - ipython-genutils==0.2.0
    - jmespath==0.9.5
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.2.1
    - nbformat==5.0.5
    - packaging==20.3
    - pandocfilters==1.4.2
    - pathtools==0.1.2
    - pillow==7.1.1
    - protobuf==3.11.3
    - pydeck==0.3.0
    - pyyaml==5.3.1
    - pyzmq==19.0.0
    - requests==2.23.0
    - s3transfer==0.3.3
    - streamlit==0.57.3
    - tensorboard==1.8.0
    - tensorflow==1.8.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - toml==0.10.0
    - toolz==0.10.0
    - tornado==5.1.1
    - tzlocal==2.0.0
    - urllib3==1.25.8
    - validators==0.14.3
    - watchdog==0.10.2
    - werkzeug==1.0.1
prefix: /Users/ayushkumarshah/miniconda3/envs/tf
